# SPDX-License-Identifier: GPL-2.0
uniphier-dvb-y += hsc-dma.o hsc-css.o hsc-ts.o hsc-ucode.o hsc-core.o
uniphier-dvb-$(CONFIG_DVB_UNIPHIER_LD11) += hsc-ld11.o

obj-$(CONFIG_DVB_UNIPHIER) += uniphier-dvb.o
